# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vg9cYCnZ22MrinQ3yp_cpFcRkRFGsFio
"""

# Muhammad Dhimas Darmawan
# 065002300018

print("Masukkan data kamu dengan sesuai!")

nama = input("Masukkan nama lengkap : ")
alamat = input("Masukkan alamat/tempat tinggal : ")
kampus = input("Masukkan Nama kampus : ")
jurusan = input("Masukkan Jurusan kamu : ")
gedung = input("Dimana gedung kampus jurusan kamu (e.g, A) : ")

print("\n")
print("Berikut data kamu!")

# Muhammad Dhimas Darmawan
# 065002300018

print("Hitung Luas Ruangan")

panjang = int(input("Masukkan Panjang Ruangan: ") )
lebar = int(input("Masukkan Lebar Ruangan: " ) )
ukuran = (input("Masukkan Satuan (Meter/inci): " ) )
luas = panjang * lebar

if "Meter" in ukuran:
	print("Luas ruangan dengan panjang ", panjang, "dan lebar ", lebar, "adalah ", luas, "Meter")
elif "inci" in ukuran:
	print("Luas ruangan dengan panjang ", panjang, "dan lebar ", lebar, "adalah ", luas * 39.3700787, "inci")